name: siwatt_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  dio: ^5.7.0
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.66.0
  json_annotation: ^4.9.0
  hive_ce: ^2.18.0
  hive_ce_flutter: ^2.3.4
  mqtt_client: ^10.11.5
  intl: ^0.20.2
  wifi_iot: ^0.3.19+2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.4
  build_runner: ^2.10.5
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bottom_navigation/
    - assets/icons/dashboard_card/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
